---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: prowlarr-pv
  storageClassName: nfs-csi-appdata