---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: appdata-pv