ansible_become_pass: ENC[AES256_GCM,data:mvEv68MMzdc=,iv:EGITwVt0HlZRWEjL+RznP34UK+VUlMhlDcNT0lgZpr4=,tag:P1yKCPBhqm6QAe3cGtfp2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m2kmyszdr2978qdlwpeeyh4rxmdrj0xahpxsg7jjsz40gu04vpasha7cup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WGR4WlV1ZmU3aGYxYWpT
            eFdqSCtsSDJBRXBvU1M3SXhMK050SkZRSVhJClV5VzEvL08wOFB3QlFTRnhxWVJC
            Q2c5OWMrQ3NpYWRpeXdmWWRDVEdFeXMKLS0tIFg5ZDQ3YVg2VzZoNlZueHhWNDNW
            NUIwdCs0S2wyMWdQT1dvVlo2SHpXUTgKHS6XiLy1F4lw18rHOsDAgMubC9l5xC54
            tU7OCx3Dc6L98JL4hYzTQa0OrvXZP7m2RXLrBYBZBa71YPrQOQJ5NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T01:57:34Z"
    mac: ENC[AES256_GCM,data:6At+dAhB5KwxTG/BGKRaSwnZFCaECnr7ZxMJVFsgPtzsutbTCaplMwY8QHcdmhk4f0KyJF9Qp7b1G+Bj7pDHiOViWJ57D5q+Yh3/7eqvjvHkEqLdUvPifVYZyli6aO5LjrF5BBVaJ1LJ8RAPvJzLw8QqOk+Zmt4nPvUVW1EQx8U=,iv:s2xdo+fQe5huoV0w6BUEVmMPl7eUkaDlOVbPWgYLZ/Y=,tag:Q0EZYPDVk15gqqrHpDPZrQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
