---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-appdata
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.3
  share: /nvme
  subDir: /appdata/$${pvc.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: 
  - nfsvers=4.1