---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-appdata
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.3
  share: /nvme/appdata
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
