apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/GAVDeuyUNTgx5jyyoBWu01VzZ69tG/l,iv:iku1vTVFPAeG31hPNKrVB45h4ZC8torRizKPmI0TSow=,tag:/SYopaGvkMzfB3H+2H38Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m2kmyszdr2978qdlwpeeyh4rxmdrj0xahpxsg7jjsz40gu04vpasha7cup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVTV0ZHlvaVYzUkNPZ0JU
            RjBmdDhhcVR3N25PeEhFY0ZSUEdSRXlaQkFvCjIvOVZhRzk3R3hDYXpRUUNpZUlP
            ckVSNnFzNTZ4SklQelVXaFc4S0hFRncKLS0tIGV0VmJ3UEhwNDEwVzVZSGZxazhn
            amNhV0lHVVdVZGtPb3hyY1FpZlVHMlUKK+HhHko19fnbd1CdRRwYJgGAKelAd2iu
            wbEBNQR4WXGgRWYe0RbO/o0p/5xuKn/ECvxomOogCslMGVJVkBZBBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T01:58:11Z"
    mac: ENC[AES256_GCM,data:BU0HW00fi2SjOVzBi6YlIeKQ3MBf87HsD3SABsYp57w3nEsD3bgyNm9+5tJac9CuCqvpbU4ZdiTzngaLpp79RvMaTZvRpDVccUJjU07VDx3VGuXEMZvvWIhVwy5nIod6ini3PH7TmxHrneIO3PRzpFWFDQ8vxpaztPi2uAyJJe4=,iv:6OeNPkgEbK2QPNJa/O9dwwUzmwWnYf+2dnMsoDOph+k=,tag:Ga1iDO+VKhEfpO4XnJAkEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
