---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app radarr
  namespace: default
spec:
  interval: 2m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: 5.0.3.8127
            resources:
              requests:
                cpu: 15m
                memory: 352Mi
              limits:
                memory: 1Gi
    service:
      main:
        ports:
          http:
            port: &port 7878

    securityContext:
      privileged: true

    probes:
    #   liveness: &probes
    #     enabled: true
    #     custom: true
    #     spec:
    #       httpGet:
    #         path: /ping
    #         port: *port
    #       initialDelaySeconds: 0
    #       periodSeconds: 10
    #       timeoutSeconds: 1
    #       failureThreshold: 3
    #   readiness: *probes
      startup:
        enabled: false

    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: mdi:filmstrip
          hajimari.io/group: "media"
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: radarr-pvc
        subPath: ./radarr
      media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /media
      downloads:
        enabled: true
        existingClaim: downloads-nfs-share-pvc
        mountPath: /downloads