---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mdi:filmstrip
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mdi:filmstrip-pv
  storageClassName: nfs-csi