---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: radarr-pv
  storageClassName: nfs-csi