apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:P8lIgRQWKUePCuP3+UKYvY72,iv:OsvDGEnA1trmJLVqA2IOW8h7qUKUDPFSH3cwLFyPL6A=,tag:4t+gQRXx5OYIU1LzJKj9+A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NsrYwXJcdYHVMc+Nssg8toLaMrWxgW5feNs9hFmpBX/USx/v,iv:i82iUSjFgS7IuiUxiDJUvUYSR1POod0CZRbItbJV7QE=,tag:Cz3X5XXP02vG0KphNtji8A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:H1zClo/lw8Uc0AWB,iv:U83ZW+HY4tPpc3To6vIvHLbYsv2duyGgJQCe8SpFwJY=,tag:9E7xkZpTDjfBbxcPFim5EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m2kmyszdr2978qdlwpeeyh4rxmdrj0xahpxsg7jjsz40gu04vpasha7cup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJekJ5cDhHWGRMUjJYcy8w
            eVEzdDM3eEtFNUJrS1pyczVWTVR3SGdkUzFnClcrOG1nNWJYRitDbzRlcGg3eFps
            Mm9wcG1MV1B2cHc2Z0tUemkyRDdKZlUKLS0tIE8rSDlPM1pHTFNpQ0JaS0hGV1lt
            ZUo5TVpUMm83bS9wdEF0M3Y1ZjV4UEEKVAPqRYVFfunqb497XHK7l2+14KQlfuu8
            sq/FQ9mOcDkz8GMIlgzteP2upbp3PJkyAb3xyK2rseTmrLdyTKm1rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-27T23:31:24Z"
    mac: ENC[AES256_GCM,data:pTeMgT860TPbLdDNSHALDBP7y9A/Nz3F1BQeShKqjIUVU8QlOW2R/B4xsVDYRY0oh7qBOI3xBANPcDrOgK1viELqiyot3cHZCGu/bjFnNfGNv94RJIkxRrgyYt6sDeaH+sc4f7aEqflqYr/EFIoHbjwv3gsZQEOyDDGLxJ04eEs=,iv:ii2MEgObH/c20R4KhRGshyIjR1nMNHAQir6pLqcDfRI=,tag:LnJN1YfK42zRQZ6sMcPByg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
