apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:audKpE1pNsmcnO1P,iv:MsFEMffncjw/EEFAeJsfhScKmcO3oBNvSsmh+BLzDHw=,tag:t+2chwwC/06bE68R25054A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m2kmyszdr2978qdlwpeeyh4rxmdrj0xahpxsg7jjsz40gu04vpasha7cup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN29DdEJGTktYWVd6Ynk3
            R3Z3UGFjNG9LTVNEdHFncEFPYkx4L0hHbUNnCmlEUkdBd2FXK3UzenJCbjJ5czVx
            WG1jUFI4RFovbUhCR24ybnd5d3MxeEkKLS0tIDJIUDJROE92Tkg0U3NJankyOFpG
            VksrNWErQTVKL1E4Z2w2dk13S0VUUzQKH6He5S23LeTPTO48H9MxyO3eK5jtHQYd
            hcRwX5egGdF4Db3fKDX0K0oRrkSp3lhJ8HpGLPsQFYRkI8X9YKq4yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-27T23:31:24Z"
    mac: ENC[AES256_GCM,data:b74ICMBxmGjDdP3MsYCC3MEcEuCfK88W7mcMCV8C1Dki1/OYYgCQTrrC62hfcjGK8KxCa1HvauGQzv9CgT/Pp/YkkbgE1ZU5B4H6D1qgAuIVWWTBPrpHTHjH99NZF+666DC3+x5sKGSR/5HtcB5iSo05k2ecwiyfQJW8R26raFg=,iv:bVFF5dFKqnDWGH2d+1Uu1gQ2TCELBRkhy8r9kOenjeo=,tag:maZChWTV9O9YjXMunwLGhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
