---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plex
  namespace: default
spec:
  interval: 2m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/onedr0p/plex-beta
      tag: 1.32.7.7571-13cdc68dc@sha256:a9474ff865f654cee7069357ce52469ab2929abdc1133568ba07b5fe83d09e9f
    env:
      TZ: "${TIMEZONE}"
      ADVERTISE_IP: "https://plex.${SECRET_DOMAIN}:443,http://192.168.1.147:32400"
      ALLOWED_NETWORKS: "10.0.0.0/8,172.16.0.0/16,192.168.0.0/16"
      HOSTNAME: "plex"
      PLEX_UID: 0
      PLEX_GID: 0
      PLEX_CLAIM: claim-z7szjbsqJyE8cg9umvLJ

    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.1.148"
        ports:
          http:
            port: &port 32400

    securityContext:
      privileged: true

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /identity
            port: *port
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3

    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          hajimari.io/icon: "plex"
          hajimari.io/group: "media"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: plex
        subPath: ./plex
      media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /media
