---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plex
  namespace: default
spec:
  interval: 2m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.32.1.6999-91e1e2e2c
    env:
      TZ: "${TIMEZONE}"
      ADVERTISE_IP: "https://plex.${SECRET_DOMAIN}"
      PLEX_UID: 0
      PLEX_GID: 0
    
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0

    service:
      main:
        ports:
          http:
            port: &port 32400

    securityContext:
      privileged: true

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /identity
            port: *port
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: "plex"
          hajimari.io/group: "media"
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: plex
        subPath: ./plex
      media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /media