---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: plex-pv
  storageClassName: nfs-csi