---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: default
spec:
  interval: 2m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.703

    env:
      TZ: "${TIMEZONE}"
      SONARR__APPLICATION_URL: "https://sonarr.${SECRET_DOMAIN}"
      SONARR__LOG_LEVEL: info

    service:
      main:
        ports:
          http:
            port: &port 8989

    securityContext:
      privileged: true

    # probes:
    #   liveness: &probes
    #     enabled: true
    #     custom: true
    #     spec:
    #       httpGet:
    #         path: /ping
    #         port: *port
    #       initialDelaySeconds: 0
    #       periodSeconds: 10
    #       timeoutSeconds: 1
    #       failureThreshold: 3
    #   readiness: *probes
    #   startup:
    #     enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: mdi:television-classic
          hajimari.io/group: "media"
        hosts:
          - host: &host "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: sonarr
        subPath: ./sonarr
      media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /media
      downloads:
        enabled: true
        existingClaim: downloads-nfs-share-pvc
        mountPath: /downloads