---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: sonarr-pv
  storageClassName: nfs-csi