apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:nJM6cMFDXfebhlcunUi7EwjopgsnucUyqpRGXwPqCepFrHyu,iv:6rghdXIQM4d8A+Ar8DPFq+AULrcHy3qm2fKiKXV4A1I=,tag:DEZZN9qflx/FhG70YKfXIA==,type:str]
    credentials.json: ENC[AES256_GCM,data:KKDcVKQSFOBd2lr70wxGHUahKPWViPu4Pkz0RxIyyitPdM65GUON7ZEZm+b0UgCSBig9MCfcQ5QWDmlSqkrJ6rtglxFknwKJhD4hpXjL8poimczeCQJhV67oWTDfAqQ5Q7WkWwZ3k+ruIQdhIWof1qW6czVBGMT0KTO8PzTcFuH0HF5v9FH5W/vj4NE1bemfqrFwx/cs+n96y2Jkiiu/SLtO64vFamFhBerBY/1nEQ==,iv:I6PlmOw6+GlM8Si0NF4H92rMQUH7hVmUJ5HePWAr+O8=,tag:2PMOAND1qBSiKD2ymEvscQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m2kmyszdr2978qdlwpeeyh4rxmdrj0xahpxsg7jjsz40gu04vpasha7cup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmb2N3ZEdjQ09UZDZVWjFX
            ckVRNGlyeUlvaEc1UFRsWTQ3dVNGa0cxdmx3CjZ5cU9tM1pET2hlYU1TSUVrQTdy
            djNSMW44YkdYZU94bUNEOGJlNXhGWEEKLS0tIFViYy9MT3F4bDRKMzE4cHBta3Fr
            dUcwd2NrRkZybzg1THBNRUpUWDVJY0UKPDgon78pt6wtRpsFZSBhkMS+I/ZS2KWR
            q1qN7T7Vk2poH9MCKrk1vnpMgQ6a3WOU9yix8nak8Mrx8e2iJUu+yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T10:24:10Z"
    mac: ENC[AES256_GCM,data:dU95OWbAqqluSG2rxnsSOPXhnOxZh4ANOTR/tUpSGjkLFTZgQBGv/Ds+H6zKu3kK5JYtUTjKzxeGKoEVxCqMqUjjj+f1sfcqH7o7pIBjTuzunygqx7H2QExK4GK2eewJRfYr2OgJetp/Rkq88IpozDwzcr4PDnCY6iUYsRfrNWE=,iv:TZjVrkhg4M4vNNxompx1eeenPWKF7QHSsFrOu5zjuPs=,tag:E/rx/PbhOjQ1F/fo6dEK6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
