---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app recyclarr
  namespace: default
spec:
  interval: 2m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
    type: statefulset
    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: 6.0.1
    env:
      TZ: "${TIMEZONE}"

    service:
      main:
        enabled: false

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: recyclarr
        subPath: ./recyclarr
      config-file:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        subPath: recyclarr.yml
        mountPath: /config/recyclarr.yml
        readOnly: true

    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 500Mi